name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Libcurl 
      run: sudo apt-get install libcurl4 libcurl4-openssl-dev
    - name: make god
      run: make god
      
  build-windows:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Install mingw
      run: sudo apt-get install mingw-w64
    - name: Install Libcurl 
      run: sudo apt-get install libcurl4 libcurl4-openssl-dev
    - name: make god
      run: x86_64-w64-mingw32-gcc -o god.exe Gods_seedfinder.o layers.o generator.o finders.o util.o -lm -pthread -lcurl
