name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Libcurl 
      run: sudo apt-get install libcurl4 libcurl4-openssl-dev
    - name: make god
      run: make god
      
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cygwin
        run: choco install --no-progress cygwin
      - name: Install cygwin additional packages
        run: |
          C:\tools\cygwin\cygwinsetup.exe -qgnNdO -R C:/tools/cygwin -s http://cygwin.mirror.constant.com -P libcurl4,libcurl-devel,curl
        shell: cmd
      - name: make god
        run: make god
