name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
 

    steps:
    - uses: actions/checkout@v2
    - name: Install Libcurl 
      run: sudo apt-get install libcurl4 libcurl4-openssl-dev
    - name: make god
      run: make god
